### ISSUE TITLE
Qeustion/Feature request: Is it possible to sufix the commit messages with the branch name? 

### ISSUE THREAD

**Issue by joaomper-TE** [christian-gama/autocommit#1]
In my company we always format the commit messages including the branch name. 
E.g. for a branch `AS-123`: 
`AS-123: commit message`

Is it possible to configure this tool to do so?

**Comment by christian-gama** [comment]
Currently, there is no way of doing it because the tool adheres to the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#specification) specifications. However, I could allow the user to edit the system instructions, so you could ask the system to include the branch name in your commit message.

**Comment by joaomper-TE** [comment]
If you can, that would be awesome. If not, I can do a PR maybe in a while.

**Comment by christian-gama** [comment]
I can do that, no worries. :smile:

**Comment by christian-gama** [comment]
Feature implemented. Run `autocommit edit` to open the system default message. In case you mess up, if the text file is empty or does not exist, the tool will recreate it.

[v1.5.0](https://github.com/christian-gama/autocommit/releases/tag/v1.5.0)

**Comment by joaomper-TE** [comment]
Awesome, thanks! will try it in a bit
